blank_issues_enabled: true
contact_links:
  - name: Meldt een veiligheidsprobleem / Report a security vulnerability
    url: https://github.com/open-formulieren/open-forms/security/policy
    about: Bekijk ons beveiligingsbeleid voor meer informatie / Please review our security policy for more details
  - name: Ondersteuning met prioriteit / Priority support
    url: https://opengem.nl/contact/
    about: Neem direct contact met ons op / Contact us directly to get priority support.
