version: '3.8'

name: rx-mission

services:
  rx_mission:
    build: ./rx-mission
    ports:
      - "81:81"
    volumes:
      - ./rx-mission/:/app/

networks:
  open-forms-dev:
    name: open-forms-dev
